// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proyecto1Bases.Data;

namespace Proyecto1Bases.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211018015719_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Proyecto1Bases.Models.Cliente", b =>
                {
                    b.Property<string>("ccedula")
                        .HasColumnType("text");

                    b.Property<string>("cconstrasenia")
                        .HasColumnType("text");

                    b.Property<int>("cedad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("cfecha_nacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("cnombre_completo")
                        .HasColumnType("text");

                    b.Property<string>("ctelefono")
                        .HasColumnType("text");

                    b.Property<string>("cusuario")
                        .HasColumnType("text");

                    b.HasKey("ccedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyecto1Bases.Models.Empleado", b =>
                {
                    b.Property<string>("ecedula")
                        .HasColumnType("text");

                    b.Property<string>("econstrasenia")
                        .HasColumnType("text");

                    b.Property<int>("eedad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("efecha_nacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("enombre_completo")
                        .HasColumnType("text");

                    b.Property<string>("etelefono")
                        .HasColumnType("text");

                    b.Property<string>("eusuario")
                        .HasColumnType("text");

                    b.Property<string>("rol")
                        .HasColumnType("text");

                    b.HasKey("ecedula");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Proyecto1Bases.Models.Pelicula", b =>
                {
                    b.Property<string>("pnombre_original")
                        .HasColumnType("text");

                    b.Property<string>("clasificacion")
                        .HasColumnType("text");

                    b.Property<string>("director")
                        .HasColumnType("text");

                    b.Property<string>("pduracion")
                        .HasColumnType("text");

                    b.Property<string>("pimagen")
                        .HasColumnType("text");

                    b.Property<string>("pnombre")
                        .HasColumnType("text");

                    b.Property<string>("protagonistas")
                        .HasColumnType("text");

                    b.HasKey("pnombre_original");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("Proyecto1Bases.Models.Proyeccion", b =>
                {
                    b.Property<int>("proyeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("cine")
                        .HasColumnType("text");

                    b.Property<string>("horario")
                        .HasColumnType("text");

                    b.Property<string>("sala")
                        .HasColumnType("text");

                    b.HasKey("proyeccionId");

                    b.ToTable("Proyecciones");
                });

            modelBuilder.Entity("Proyecto1Bases.Models.Sala", b =>
                {
                    b.Property<string>("sid")
                        .HasColumnType("text");

                    b.Property<int>("cantidad_columnas")
                        .HasColumnType("integer");

                    b.Property<int>("cantidad_filas")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_sucursal")
                        .HasColumnType("text");

                    b.Property<int>("scapacidad")
                        .HasColumnType("integer");

                    b.HasKey("sid");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Proyecto1Bases.Models.Sucursal", b =>
                {
                    b.Property<string>("nombre_cine")
                        .HasColumnType("text");

                    b.Property<int>("cantidad_salas")
                        .HasColumnType("integer");

                    b.Property<string>("ubicacion")
                        .HasColumnType("text");

                    b.HasKey("nombre_cine");

                    b.ToTable("Sucursales");
                });
#pragma warning restore 612, 618
        }
    }
}
