// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proyecto1Bases.Data;

namespace Proyecto1Bases.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Proyecto1Bases.Models.Pelicula", b =>
                {
                    b.Property<string>("pnombre_original")
                        .HasColumnType("text");

                    b.Property<string>("clasificacion")
                        .HasColumnType("text");

                    b.Property<string>("director")
                        .HasColumnType("text");

                    b.Property<string>("pduracion")
                        .HasColumnType("text");

                    b.Property<string>("pimagen")
                        .HasColumnType("text");

                    b.Property<string>("pnombre")
                        .HasColumnType("text");

                    b.Property<string>("protagonistas")
                        .HasColumnType("text");

                    b.HasKey("pnombre_original");

                    b.ToTable("Peliculas");
                });
#pragma warning restore 612, 618
        }
    }
}
